version: '3'
services:
#Docker Networks
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - "3033:3000"
    networks:
      - app-network
    command: npm start
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  dbpostdata:
    driver: local
  redis-data:
