version: "3"
services:
  #Docker Networks
  clientreact:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "3033:3000"
    networks:
      - app-network
    command: npm start

    #Docker Networks
  backend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "3333:3001"
    networks:
      - app-network
    command: npm start
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
